FROM apache/airflow:2.9.2-python3.11

USER root
RUN apt-get update && apt-get install -y --no-install-recommends build-essential && \
    rm -rf /var/lib/apt/lists/*
USER airflow

COPY requirements-base.txt /requirements-base.txt
RUN pip install --no-cache-dir -r /requirements-base.txt