FROM python:3.11-slim

RUN apt-get update && apt-get install -y --no-install-recommends build-essential && \
    rm -rf /var/lib/apt/lists/*

COPY requirements-streamlit.txt /requirements.txt
COPY requirements-base.txt /requirements-base.txt
RUN pip install --no-cache-dir -r /requirements.txt

WORKDIR /app
COPY app /app/app
COPY src /app/src

ENV ARTIFACTS_DIR=/app/models
EXPOSE 8501
CMD ["streamlit", "run", "app/streamlit_app.py", "--server.address=0.0.0.0", "--server.port=8501"]
